host_project = "/home/cybernetics/Documents/Projects/University/thesis/DCM-RUST/runtime-code-mobility-demo"
server_code_distributor = "/home/cybernetics/Documents/Projects/University/thesis/DCM-RUST/code-distributor"
client_code_distributor = "/home/cybernetics/Documents/Projects/University/thesis/DCM-RUST/runtime-code-mobility-demo/src/frontend/static/js/CodeDistributor"
compilation_max_thread_pool = 6
compilation_enable_release_mode = true
compilation_enable_wasm_optimization = true
