version: '3.7'

services:
  wasm-generator:
    image: pratik90/wasm-generator
    environment:
      project: "/demo-app"
      server_fragments_dir: "/code-distributor/fragments"
      client_code_distributor_dir: "/project/src/frontend/static/js/CodeDistributor"
      release_mode: "true"
    #      optimize_wasm: "true"
    #      max_thread_pool: 1
    volumes:
      - ./runtime-code-mobility-demo:/demo-app
      - ./code-distributor:/code-distributor
