version: '3.7'

services:
  code-distributor:
    image: pratik90/code-distributor
    environment:
      app_port: 8082
    ports:
      - "8082:8082"

  runtime-code-mobility-demo:
    image: pratik90/runtime-code-mobility-demo
    environment:
      app_port: 8081
      code_distributor_ws_url: "ws://localhost:8082/ws/"
      code_distributor_api_url: "http://localhost:8082/api/"
    ports:
      - "8081:8081"
