version: '3.7'

services:
  wasm-generator:
#    user: "1000:1000"
    image: pratik90/thesis-wasm-generator:latest
    pull_policy: always
    environment:
      host_project_root: "/project"
      server_code_distributor_location: "/project/code-distributor"
      client_code_distributor_location: "/project/src/frontend/static/js/CodeDistributor"
      compilation_enable_release_mode: "true"
      enable_wasm_optimization: "true"
      app_port: "8081"
      code_distributor_port: "51335"
#      skip_wasm_generator: "true"
      compilation_max_thread_pool: 6
    ports:
      - "8081:8081"
      - "51335:51335"
    volumes:
      - ./:/project
